/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.sbapr.gui;

import java.awt.Frame;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import cz.muni.fi.sbapr.dataprocessing.DataManager;
import cz.muni.fi.sbapr.models.CreateNewCardModel;
import cz.muni.fi.sbapr.models.OperationRecord;

/**
 *
 * @author Martin
 */
public class CreateNewJCardDialog extends javax.swing.JDialog {
    /**
     * Creates new form CreateNewCardDialog
     * @param parent
     * @param modal
     * @param createNewCardModel
     */
    public CreateNewJCardDialog(Frame parent, boolean modal, CreateNewCardModel createNewCardModel) {
        super(parent, modal);
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                CreateNewJCardDialog.this.setVisible(false);
            }
        });
        this.createNewCardModel = createNewCardModel;
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createNewCardJLabel = new javax.swing.JLabel();
        sourceDirectoryJLabel = new javax.swing.JLabel();
        sourceDirectoryJTextField = new javax.swing.JTextField();
        sourceDirectoryJButton = new javax.swing.JButton();
        destinationDirectoryJLabel = new javax.swing.JLabel();
        createNewCardJButton = new javax.swing.JButton();
        destinationDirectoryJTextField = new javax.swing.JTextField();
        destinationDirectoryJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        createNewCardJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        createNewCardJLabel.setText("Create new card");

        sourceDirectoryJLabel.setText("Select directory in which are measurements for a new card:");

        sourceDirectoryJButton.setText("...");
        sourceDirectoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceDirectoryJButtonActionPerformed(evt);
            }
        });

        destinationDirectoryJLabel.setText("Select destination directory:");

        createNewCardJButton.setText("Create");
        createNewCardJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewCardJButtonActionPerformed(evt);
            }
        });

        destinationDirectoryJButton.setText("...");
        destinationDirectoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationDirectoryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createNewCardJLabel)
                            .addComponent(sourceDirectoryJLabel)
                            .addComponent(destinationDirectoryJLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sourceDirectoryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sourceDirectoryJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createNewCardJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(destinationDirectoryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinationDirectoryJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewCardJLabel)
                .addGap(18, 18, 18)
                .addComponent(sourceDirectoryJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceDirectoryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceDirectoryJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinationDirectoryJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationDirectoryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationDirectoryJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(createNewCardJButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewCardJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewCardJButtonActionPerformed
        if (sourceDirectoryJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Source directory path cannot be empty.");
        } else if (destinationDirectoryJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Destination directory path cannot be empty.");
        } else {
            List<OperationRecord> operationRecordsList = DataManager.scanDirectory(sourceDirectoryJTextField.getText());
            if (operationRecordsList == null || operationRecordsList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "There are no valid CSV files in the source directory.");
                return;
            }
            createNewCardModel.setSourceDirectory(sourceDirectoryJTextField.getText());
            createNewCardModel.setDestinationDirectory(destinationDirectoryJTextField.getText());
            createNewCardModel.setOperationRecords(operationRecordsList);
            createNewCardModel.setFinishedProcess(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_createNewCardJButtonActionPerformed

    private void sourceDirectoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceDirectoryJButtonActionPerformed
        JFileChooser jFileChooser = returnJFileChooserResult();
        if (jFileChooser != null && jFileChooser.getSelectedFile() != null)
            sourceDirectoryJTextField.setText(jFileChooser.getSelectedFile().getPath());
    }//GEN-LAST:event_sourceDirectoryJButtonActionPerformed

    private void destinationDirectoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationDirectoryJButtonActionPerformed
        JFileChooser jFileChooser = returnJFileChooserResult();
        if (jFileChooser != null && jFileChooser.getSelectedFile() != null)
            destinationDirectoryJTextField.setText(jFileChooser.getSelectedFile().getPath());
    }//GEN-LAST:event_destinationDirectoryJButtonActionPerformed

    private JFileChooser returnJFileChooserResult() {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
            return jFileChooser;
        return null;
    }
    
    public CreateNewCardModel createNewCardModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewCardJButton;
    private javax.swing.JLabel createNewCardJLabel;
    private javax.swing.JButton destinationDirectoryJButton;
    private javax.swing.JLabel destinationDirectoryJLabel;
    private javax.swing.JTextField destinationDirectoryJTextField;
    private javax.swing.JButton sourceDirectoryJButton;
    private javax.swing.JLabel sourceDirectoryJLabel;
    private javax.swing.JTextField sourceDirectoryJTextField;
    // End of variables declaration//GEN-END:variables
}
